/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RouteImport } from './routes/Route'
import { Route as WatchEpisodeIdImport } from './routes/watch.$episodeId'

// Create/Update Routes

const RouteRoute = RouteImport.update({
  id: '/Route',
  path: '/Route',
  getParentRoute: () => rootRoute,
} as any)

const WatchEpisodeIdRoute = WatchEpisodeIdImport.update({
  id: '/watch/$episodeId',
  path: '/watch/$episodeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Route': {
      id: '/Route'
      path: '/Route'
      fullPath: '/Route'
      preLoaderRoute: typeof RouteImport
      parentRoute: typeof rootRoute
    }
    '/watch/$episodeId': {
      id: '/watch/$episodeId'
      path: '/watch/$episodeId'
      fullPath: '/watch/$episodeId'
      preLoaderRoute: typeof WatchEpisodeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/Route': typeof RouteRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}

export interface FileRoutesByTo {
  '/Route': typeof RouteRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/Route': typeof RouteRoute
  '/watch/$episodeId': typeof WatchEpisodeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/Route' | '/watch/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/Route' | '/watch/$episodeId'
  id: '__root__' | '/Route' | '/watch/$episodeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RouteRoute: typeof RouteRoute
  WatchEpisodeIdRoute: typeof WatchEpisodeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  RouteRoute: RouteRoute,
  WatchEpisodeIdRoute: WatchEpisodeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/Route",
        "/watch/$episodeId"
      ]
    },
    "/Route": {
      "filePath": "Route.tsx"
    },
    "/watch/$episodeId": {
      "filePath": "watch.$episodeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
