name: Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ master ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push to Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zakism/pka-index-frontend
          tags: latest
