name: Deploy

on:
  push:
    paths-ignore:
      - 'README.md'
    branches: [ master ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=zakism/pka-index-frontend:latest
          cache-to: type=inline
          tags: zakism/pka-index-frontend:latest
