name: Yarn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: build
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
