name: Yarn CI
on: [push]
jobs:
  build:
    name: Install/Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
      - name: Yarn install
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
      - name: Yarn build
        with:
          cmd: build # will run `yarn build` command
